version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app_DockerFile
    depends_on:
      - db
  db:
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8; SET CHARACTER SET utf8mb4;'
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    build:
      context: .
      dockerfile: web_DockerFile
    depends_on:
      - app
    ports:
      - 88:80
