version: "3.3"
services:
  db:
    image: mysql:5.7
    env_file: backend/.env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8; SET CHARACTER SET utf8mb4;'
    ports:
      - "3308:3306"
  rails_server:
    build:
      context: .
      dockerfile: Dockerfile-web-prod
    env_file: backend/.env
    environment:
      RAILS_ENV: production
    volumes:
      - ./backend:/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  node_server:
    build:
      context: .
      dockerfile: Dockerfile-node-server
    tty: true
    volumes:
      - ./frontend:/frontend
    command: node server
    ports:
      - "80:5000"
