version: "3.3"
services:
  db:
    image: mysql
    env_file: backend/.env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8; SET CHARACTER SET utf8mb4;'
    ports:
      - "3308:3306"
  rails_server2:
    build:
      context: .
      dockerfile: Dockerfile-web
    env_file: backend/.env
    tty: true
    restart: always
    volumes:
      - ./backend:/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: rails s -b 0.0.0.0
  vue_server:
    build:
      context: .
      dockerfile: Dockerfile-vue-server
    volumes:
      - ./frontend:/frontend
    tty: true
    restart: always
    command: npm run dev
    ports:
      - "8080:8080"
