version: '3'
services:
  web:
    build:
      context: .
      dockerfile: node_Dockerfile
    tty: true
    volumes:
      - .:/vue_app
    command: npm run dev
    ports:
      - "5001:5000"
      - "8081:8080"
