version: "3.3"
services:
  db:
    image: mysql
    env_file: .env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8; SET CHARACTER SET utf8mb4;'
    ports:
      - "3308:3306"
  web:
    build:
      context: .
      dockerfile: Dockerfile-web-prod
    env_file: .env
    environment:
      RAILS_ENV: production
    volumes:
      - .:/server
    ports:
      - "3000:3000"
    depends_on:
      - db
